name: CI

on:
  pull_request: {}
  push: { branches: [ master ] }

jobs:
  check:
    strategy:
      matrix:
        module:
          - testcontainers
          - cassandra
          - clickhouse
          - cockroachdb
          - couchbase
          - database-commons
          - db2
          - dynalite
          - elasticsearch
          - influxdb
          - jdbc
          - jdbc-test
          - junit-jupiter
          - kafka
          - localstack
          - mariadb
          - mockserver
          - mssqlserver
          - mysql
          - neo4j
          - nginx
          - oracle-xe
          - orientdb
          - postgresql
          - presto
          - pulsar
          - r2dbc
          - rabbitmq
          - selenium
          - spock
          - toxiproxy
          - vault
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '1.8'
      - name: Cache Gradle Home files
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-home-core_check-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-home-core_check-
            ${{ runner.os }}-gradle-home-core_check-
            ${{ runner.os }}-gradle-home-
      - name: Clear existing docker image cache
        run: docker image prune -af
      - name: Build and test with Gradle (testcontainers:check)
        run: |
          ./gradlew --no-daemon --continue --scan --info ${{matrix.module}}:check
      - name: Aggregate test reports with ciMate
        if: always()
        env:
          CIMATE_PROJECT_ID: 2348n4vl
        run: |
          wget -q https://get.cimate.io/release/linux/cimate
          chmod +x cimate
          ./cimate "**/TEST-*.xml"
