name: CI

on:
  pull_request: {}
  push: { branches: [ master ] }

jobs:
  find_gradle_jobs:
    runs-on: ubuntu-18.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: echo "::set-output name=matrix::{\"module\":$(.github/workflows/scripts/find_gradle_jobs.sh)}"
  check:
    needs: find_gradle_jobs
    strategy:
      matrix: ${{ fromJson(needs.find_gradle_jobs.outputs.matrix) }}
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '1.8'
      - name: Cache Gradle Home files
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-home-${{matrix.module}}_check-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-home-${{matrix.module}}_check-
            ${{ runner.os }}-gradle-home-${{matrix.module}}_check-
            ${{ runner.os }}-gradle-home-
      - name: Clear existing docker image cache
        run: docker image prune -af
      - name: Build and test with Gradle (${{matrix.module}}:check)
        run: |
          ./gradlew --no-daemon --continue --scan --info ${{matrix.module}}:check
      - name: Aggregate test reports with ciMate
        if: always()
        env:
          CIMATE_PROJECT_ID: 2348n4vl
        run: |
          wget -q https://get.cimate.io/release/linux/cimate
          chmod +x cimate
          ./cimate "**/TEST-*.xml"
